---
branches:
  - name: master
  - name: beta
    prerelease: true
repositoryUrl: https://github.com/inskribe/sandbox.git

tagFormat: v${version}

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/github'
  -   - '@semantic-release/git'
      - assets: [CHANGELOG.md, ./dist/RicePaper]
