---
name: PR Validation

on:
  pull_request:
    branches: [next]

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install commitlint
        run: npm install --no-save @commitlint/{config-conventional,cli}

      - name: Lint PR commits
        run: |
          COMMITS=$(git rev-list origin/${{ github.base_ref }}..HEAD)
          echo "$COMMITS" | xargs -I {} git show -s --format=%B {} | npx commitlint

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Build binaries
        run: |-
          go mod download
          GOOS=linux GOARCH=${{ matrix.arch }} \
          go build -o RicePaper-linux-${{ matrix.arch }} ./cmd/application/main.go
