---
name: Release
run-name: Release Action
on:
  push:
    branches: [master, beta]
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Set output names
        run: echo "BINARY_NAME=RicePaper-${{ matrix.os }}-${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          go mod download
          GOOS=linux GOARCH=${{ matrix.arch }} \
          go build -o RicePaper-linux-${{ matrix.arch }} ./cmd/application/main.go

      - name: Archive
        run: |
          mkdir -p release
          cp $BINARY_NAME application_config.yml README.md release/
          tar -czvf $BINARY_NAME.tar.gz -C release .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}.tar.gz
          path: ${{ env.BINARY_NAME }}.tar.gz

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files
        run: ls -R artifacts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Aduit Signatures
        run: npm audit signatures

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npx semantic-release
