---
name: Release
on:
  push:
    branches:
      - master
      - beta
# on push to branch master: preform jobs.

# describe jobs
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Build Project
        run: |
          go mod tidy
          go build -v -o ./bin/release ./cmd/application/main.go 

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: npx semantic-release
